[book]
authors = []
language = "en"
multilingual = false
src = "src"
default="rust"

[output.html.playground]
editable = true 

[output.html]
mathjax-support = true
default-theme = "navy"
preferred-dark-theme = "navy"
curly-quotes = true
copy-fonts = true
additional-css = ["global.css"]
additional-js = ["global.js"]
no-section-label = false
git-repository-url = "https://github.com/KorieDrakeChaney/Artificial-Life-Book"
git-repository-icon = "fa-github"
site-url = "https://koriedrakechaney.github.io/Artificial-Life-Book/"
input-404 = "not-found.md"